name: 'Setup Step'
description: 'Setup Step'
author: 'Tycho Bokdam'

runs:
  using: "composite"
  steps:
    - name: Cache node modules
      id: cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/Cypress
          **/node_modules
        key: cache-node-modules-${{ hashFiles('yarn.lock') }}

    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v2

